version: ~> 1.0
os: linux
dist: xenial
language: node_js
node_js:
  - "12"

cache: yarn

git:
  depth: 3

branches:
  only:
    - main

install:
  - yarn

before_script:
  - yarn build

script:
  - yarn lint